version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - ./init/init-db:/docker-entrypoint-initdb.d/

  restful-service:
    build:
      context: .
      dockerfile: deployments/Dockerfile
    environment:
      DATABASE_URL: postgres://user:password@db:5432/database?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db

  grpc-service:
    build:
      context: .
      dockerfile: deployments/grpc.Dockerfile
    environment:
      DATABASE_URL: postgres://user:password@db:5432/database?sslmode=disable
    ports:
      - "50051:50051"
    depends_on:
      - db
