basePath: /
host: localhost:1323
info:
  contact: {}
  description: This is a simple Hello World API.
  title: Hello World API
  version: "1.0"
paths:
  /:
    get:
      description: Responds with 'Hello, World!'
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Echo Hello World
      tags:
      - Hello
swagger: "2.0"
