// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.1
// source: glossary.proto

package glossary

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlossaryTerm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Term          string                 `protobuf:"bytes,2,opt,name=term,proto3" json:"term,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlossaryTerm) Reset() {
	*x = GlossaryTerm{}
	mi := &file_glossary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlossaryTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlossaryTerm) ProtoMessage() {}

func (x *GlossaryTerm) ProtoReflect() protoreflect.Message {
	mi := &file_glossary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlossaryTerm.ProtoReflect.Descriptor instead.
func (*GlossaryTerm) Descriptor() ([]byte, []int) {
	return file_glossary_proto_rawDescGZIP(), []int{0}
}

func (x *GlossaryTerm) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GlossaryTerm) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *GlossaryTerm) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GlossaryTermRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlossaryTermRequest) Reset() {
	*x = GlossaryTermRequest{}
	mi := &file_glossary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlossaryTermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlossaryTermRequest) ProtoMessage() {}

func (x *GlossaryTermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_glossary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlossaryTermRequest.ProtoReflect.Descriptor instead.
func (*GlossaryTermRequest) Descriptor() ([]byte, []int) {
	return file_glossary_proto_rawDescGZIP(), []int{1}
}

func (x *GlossaryTermRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

type GlossaryTerms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Terms         []*GlossaryTerm        `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlossaryTerms) Reset() {
	*x = GlossaryTerms{}
	mi := &file_glossary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlossaryTerms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlossaryTerms) ProtoMessage() {}

func (x *GlossaryTerms) ProtoReflect() protoreflect.Message {
	mi := &file_glossary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlossaryTerms.ProtoReflect.Descriptor instead.
func (*GlossaryTerms) Descriptor() ([]byte, []int) {
	return file_glossary_proto_rawDescGZIP(), []int{2}
}

func (x *GlossaryTerms) GetTerms() []*GlossaryTerm {
	if x != nil {
		return x.Terms
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_glossary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_glossary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_glossary_proto_rawDescGZIP(), []int{3}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_glossary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_glossary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_glossary_proto_rawDescGZIP(), []int{4}
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_glossary_proto protoreflect.FileDescriptor

var file_glossary_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x22, 0x54, 0x0a, 0x0c, 0x47, 0x6c,
	0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x29, 0x0a, 0x13, 0x47, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x54, 0x65, 0x72, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x22, 0x3d, 0x0a, 0x0d, 0x47,
	0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x54, 0x65, 0x72, 0x6d, 0x73, 0x12, 0x2c, 0x0a, 0x05,
	0x74, 0x65, 0x72, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6c,
	0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x2e, 0x47, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x54,
	0x65, 0x72, 0x6d, 0x52, 0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x22, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xcd, 0x02, 0x0a, 0x0f, 0x47, 0x6c, 0x6f, 0x73,
	0x73, 0x61, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x65, 0x72, 0x6d, 0x73, 0x12, 0x0f, 0x2e, 0x67, 0x6c, 0x6f,
	0x73, 0x73, 0x61, 0x72, 0x79, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x67, 0x6c,
	0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x2e, 0x47, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x54,
	0x65, 0x72, 0x6d, 0x73, 0x12, 0x46, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x42,
	0x79, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x1d, 0x2e, 0x67, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79,
	0x2e, 0x47, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x2e,
	0x47, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x3c, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x16, 0x2e, 0x67, 0x6c, 0x6f,
	0x73, 0x73, 0x61, 0x72, 0x79, 0x2e, 0x47, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x54, 0x65,
	0x72, 0x6d, 0x1a, 0x16, 0x2e, 0x67, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x2e, 0x47, 0x6c,
	0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x3c, 0x0a, 0x0a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x16, 0x2e, 0x67, 0x6c, 0x6f, 0x73, 0x73,
	0x61, 0x72, 0x79, 0x2e, 0x47, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x54, 0x65, 0x72, 0x6d,
	0x1a, 0x16, 0x2e, 0x67, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x2e, 0x47, 0x6c, 0x6f, 0x73,
	0x73, 0x61, 0x72, 0x79, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x3d, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x1d, 0x2e, 0x67, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72,
	0x79, 0x2e, 0x47, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x67, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6b, 0x67, 0x2f, 0x67,
	0x6c, 0x6f, 0x73, 0x73, 0x61, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_glossary_proto_rawDescOnce sync.Once
	file_glossary_proto_rawDescData = file_glossary_proto_rawDesc
)

func file_glossary_proto_rawDescGZIP() []byte {
	file_glossary_proto_rawDescOnce.Do(func() {
		file_glossary_proto_rawDescData = protoimpl.X.CompressGZIP(file_glossary_proto_rawDescData)
	})
	return file_glossary_proto_rawDescData
}

var file_glossary_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_glossary_proto_goTypes = []any{
	(*GlossaryTerm)(nil),        // 0: glossary.GlossaryTerm
	(*GlossaryTermRequest)(nil), // 1: glossary.GlossaryTermRequest
	(*GlossaryTerms)(nil),       // 2: glossary.GlossaryTerms
	(*Empty)(nil),               // 3: glossary.Empty
	(*Status)(nil),              // 4: glossary.Status
}
var file_glossary_proto_depIdxs = []int32{
	0, // 0: glossary.GlossaryTerms.terms:type_name -> glossary.GlossaryTerm
	3, // 1: glossary.GlossaryService.GetAllTerms:input_type -> glossary.Empty
	1, // 2: glossary.GlossaryService.GetTermByTerm:input_type -> glossary.GlossaryTermRequest
	0, // 3: glossary.GlossaryService.CreateTerm:input_type -> glossary.GlossaryTerm
	0, // 4: glossary.GlossaryService.UpdateTerm:input_type -> glossary.GlossaryTerm
	1, // 5: glossary.GlossaryService.DeleteTerm:input_type -> glossary.GlossaryTermRequest
	2, // 6: glossary.GlossaryService.GetAllTerms:output_type -> glossary.GlossaryTerms
	0, // 7: glossary.GlossaryService.GetTermByTerm:output_type -> glossary.GlossaryTerm
	0, // 8: glossary.GlossaryService.CreateTerm:output_type -> glossary.GlossaryTerm
	0, // 9: glossary.GlossaryService.UpdateTerm:output_type -> glossary.GlossaryTerm
	4, // 10: glossary.GlossaryService.DeleteTerm:output_type -> glossary.Status
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_glossary_proto_init() }
func file_glossary_proto_init() {
	if File_glossary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_glossary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_glossary_proto_goTypes,
		DependencyIndexes: file_glossary_proto_depIdxs,
		MessageInfos:      file_glossary_proto_msgTypes,
	}.Build()
	File_glossary_proto = out.File
	file_glossary_proto_rawDesc = nil
	file_glossary_proto_goTypes = nil
	file_glossary_proto_depIdxs = nil
}
